# prompt/__init__.py

from .speakers_prompts import (
    SUGGEST_SPEAKERS_PROMPT,
    MATCH_SPEAKER_TO_SESSIONS_PROMPT,
    SUGGEST_SPEAKER_TOPICS_PROMPT,
    GENERATE_SPEAKER_BIO_PROMPT,
)

from .sessions_prompt import (
    SUGGEST_SESSIONS_PROMPT,
    SUGGEST_SESSION_AGENDA_PROMPT,
    MATCH_SESSIONS_TO_TRACK_PROMPT,
)

__all__ = [
    # Speakers
    "SUGGEST_SPEAKERS_PROMPT",
    "GENERATE_SPEAKER_BIO_PROMPT",
    "MATCH_SPEAKER_TO_SESSIONS_PROMPT",
    "SUGGEST_SPEAKER_TOPICS_PROMPT",
    # Sessions
    "SUGGEST_SESSIONS_PROMPT",
    "GENERATE_SESSION_ABSTRACT_PROMPT",
    "SUGGEST_SESSION_AGENDA_PROMPT",
    "MATCH_SESSIONS_TO_TRACK_PROMPT",
    "ENRICH_SESSION_CONTENT_PROMPT",
]
