name: Deploy to Dev and Test
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker build -t conferentiregistry.azurecr.io/conferenti/conferenti-web-dev:${{ github.run_number }} .
          docker push conferentiregistry.azurecr.io/conferenti/conferenti-web-dev:${{ github.run_number }}

      - name: Deploy to Kubernetes
        run: |
          # Replace the placeholder with actual run number
          envsubst < CI/dev/deployment-dev.yaml | kubectl apply -f -
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
