name: Conferenti Web - Test and Deploy Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  unit-tests:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      changed: ${{ steps.set-matrix.outputs.changed }}
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: ./conferenti-web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: conferenti-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - id: set-matrix
        run: |
          echo "matrix={\"appname\":[\"conferenti-web\"]}" >> $GITHUB_OUTPUT
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Run linter
        run: npm run lint

      - name: Type check
        run: npm run type-check
        continue-on-error: true

      - name: Run tests
        run: npm run test:ci
        env:
          CI: true
          NODE_ENV: test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            conferenti-web/test-results/
            conferenti-web/coverage/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '20.x'
        with:
          file: ./conferenti-web/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
